name: 'PR Comment'
branding:
  icon: 'award'
  color: 'white'
description: 'Comments a pull request with the provided message'
inputs: 
  message:
    description: 'Message that should be printed in the pull request'
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
